#!/bin/bash

sudo systemctl start docker
sudo docker build --tag liskbox:latest ./bin
sudo docker stop liskbox
sudo docker rm liskbox
sudo docker run -ti -v $(pwd)/app:/app -p 5000:5000 -p 4000:4000 -p 80:80 -p 6001:6001 --name liskbox liskbox
